# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Edge Of Chaos Blog
email:
description: >- # this means to ignore newlines until "baseurl:"
  This is a description of the edge of chaos blog
url: "https://humishum.github.io"
baseurl: "/blog"
twitter_username: humishum
github_username: humishum
minimal_mistakes_skin: contrast
search: true
repository: "humishum/humishum.github.io"
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.18.1
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Humdaan Mustafa"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Here's a bio about me"
  links:
    - label: "Website Home"
      icon: "fas fa-fw fa-link"
      url: "https://humdaan.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/humishum"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/humishum"
   

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/humishum"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/humishum"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://linkedin.com/humdaanm"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
